### ISSUE TITLE
Add React Library for the Frontend

### ISSUE THREAD

**Issue by williamtoll** [williamtoll/open-garden-py#1]

**Comment by raulsoledispa** [comment]
Hi, Can you give me more details?

**Comment by williamtoll** [comment]
> Hi, Can you give me more details?

 I need here  an Admin Interface with React that can interact with the API that will we develop with Django

**Comment by williamtoll** [comment]
> Hi, Can you give me more details?

We can use this component here https://devexpress.github.io/devextreme-reactive/react/scheduler/

**Comment by raulsoledispa** [comment]
Do you have a high level diagram to understand the final solution?

**Comment by williamtoll** [comment]
> Do you have a high level diagram to understand the final solution?

I will provide more details but you can check the mockup folder where you cand see what is the main idea

**Comment by williamtoll** [comment]
I will close this issue, you can check for new issues related to React
