### ISSUE TITLE
Add Django and Django Admin

### ISSUE THREAD

**Issue by williamtoll** [williamtoll/open-garden-py#2]
Add Django and Django Admin to create an API to interact with the main controller

**Comment by raulsoledispa** [comment]
Hi, Which is the goal the API ?. 
Do you have a high level diagram to understand the final solution

**Comment by Jash271** [comment]
Hey can you send the exact admin endoint requirements so I'll create a user model appropriately,and setup the authentication requirements,using django rest framework

**Comment by williamtoll** [comment]
Of course, and you can check on the mockup folder the basics screen

**Comment by Jash271** [comment]
Hey I saw the screens,didn't see an authentication image in the mock-up though😅
What I understand from the images is that you require a user to login and then add a schedule time for watering in particular zones to be logged into the database right ?

**Comment by Jash271** [comment]
I'm up for this,I'll set up the basic login auth,how are you planning  registration of users like are you going to circulate a Google form to collect their data and then a script to add all thier details from CSV or you need a normal register endpoint

**Comment by Jash271** [comment]
Either ways I am up for this,I'll set up the auth route as for this issue,which will include login registration and user model,also could you assign me this issue ?

**Comment by williamtoll** [comment]
> Either ways I am up for this,I'll set up the auth route as for this issue,which will include login registration and user model,also could you assign me this issue ?

Of course, and I can provide you the database model diagram

**Comment by Jash271** [comment]
Well that'll be great 😊

**Comment by Jash271** [comment]
Hey I've set up the basic backbone for backend, Shall I make the model upon assumption as of now for the auth part? or you're sending across the model diagram and then I'll make the changes in the model ?

**Comment by williamtoll** [comment]
I added the very beginning database model you can check on the database folder, could you add this to your Django so we can add data to prove from the Django Admin

**Comment by Jash271** [comment]
Cool,I'll look into it 👍

**Comment by Jash271** [comment]
Hey @williamtoll I've created the models and registered them in the admin ,could you kindly add hacktoberfest topic to this repo,so I'll make the pr then

**Comment by williamtoll** [comment]
> Hey @williamtoll I've created the models and registered them in the admin ,could you kindly add hacktoberfest topic to this repo,so I'll make the pr then

I already updated the topic, you can send your PR

**Comment by williamtoll** [comment]
Great thank you for your contribution
