### ISSUE TITLE
Add the new aesthetic documentation with MKdocs

### ISSUE THREAD

**Issue by williamtoll** [williamtoll/open-garden-py#22]
@nananananate coul you add the documentation, I added you as a contributor to this project

**Comment by tisuela** [comment]
Unfortunately, only the owner of the Repository can enable GitHub pages. If you do this step, I can take care of the rest.

[deploy tutorial](https://gifs.tisuela.com/open-garden/open_garden_deploy_docs.gif)

![demo](https://gifs.tisuela.com/open-garden/open_garden_deploy_docs.gif)
