### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by williamtoll** [williamtoll/open-garden-py#5]
Create a **Documentation** about the project, we need to add a documentation to help developers to understand the issues

**Comment by tisuela** [comment]
I have experience with [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/), a pretty way of displaying documentation.  I'm down to help you out, lemme know how I can better understand your tool so I can help document it!

Example of my documentation: https://docs.coursecake.tisuela.com/

**Comment by mahendrarathore1742** [comment]
can i work on this project

**Comment by williamtoll** [comment]
> I have experience with [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/), a pretty way of displaying documentation. I'm down to help you out, lemme know how I can better understand your tool so I can help document it!
> 
> Example of my documentation: https://docs.coursecake.tisuela.com/

Great, I'd like your documentation. I can provide you all the docs I have and you can start with the more good-looking documentation. I'll put all the docs in a doc folder in the branch **develop**

**Comment by williamtoll** [comment]
> can i work on this project

Of course you cand help us 👍

**Comment by tisuela** [comment]
> Great, I'd like your documentation. I can provide you all the docs I have and you can start with the more good-looking documentation. I'll put all the docs in a doc folder in the branch develop

Sounds good! I'll start working on my fork once the docs come in on branch `develop`

**Comment by williamtoll** [comment]
We can work now on specific issues for documentation, can you start with the documentation with Github Pages?
